spring.application.name=Ai-Interview-agent
server.port=6540

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.project-id=${PROJECT_ID}
spring.ai.google.genai.chat.options.temperature=0.8

spring.ai.google.genai.chat.options.response-mime-type=application/json
logging.level.org.springframework.ai=INFO